# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
after_success:
    - Rscript -e 'covr::codecov(type = "all", token = "7bbd498a-9111-4001-9f99-1873915db12e")'
notifications:
  email: false